# Generated by Django 4.2.3 on 2023-09-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('m_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('m_year', models.DateField()),
                ('m_hour', models.IntegerField()),
                ('m_img', models.ImageField(max_length=50, upload_to='')),
                ('m_link', models.URLField()),
                ('disc', models.CharField(max_length=500)),
                ('diractor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
