# Generated by Django 4.2.3 on 2023-09-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peterpeepshow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='diractor',
            new_name='director',
        ),
    ]
