# Generated by Django 4.2.3 on 2023-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peterpeepshow', '0003_alter_movies_m_hour_alter_movies_m_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='gonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=60)),
                ('go_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'gonor',
            },
        ),
    ]
