# Generated by Django 4.2.3 on 2023-10-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peterpeepshow', '0004_gonor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='action', max_length=30),
        ),
    ]
