# Generated by Django 4.2.3 on 2023-10-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peterpeepshow', '0006_alter_movies_m_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='m_hour',
            field=models.CharField(max_length=50),
        ),
    ]
